name: Sync Repository
# permissions:
#   contents: write
on: 
  push:
    branches: master
      

jobs:
  sync:
    runs-on: windows-latest
    # permissions: 
    #   contents: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: 'D:a\workRepo'
    - name: clone from personal
      run: |
        # lists all the contents of my current repo as I am checking it out.
        dir 
        # Clone personalRepo into the server using the token stored as a secret.
        git clone https://${{ secrets.SYNCINGTOKEN }}@github.com/Devarapallivamsi/personalRepo.git 
        Copy-Item -Path "D:\a\workRepo\workRepo\personalRepo\*" -Destination "D:\a\workRepo\workRepo" -Exclude "README.md" -Recurse
        # xcopy "D:\a\workRepo\workRepo\personalRepo\vectra.txt" "D:\a\workRepo\workRepo" /h
        Remove-Item -Path "D:\a\workRepo\workRepo\personalRepo" -Recurse -Force
        dir     
        git config --global user.email "vamsi@vectraglobal.com"
        git config --global user.name "vectraVamsi"
        git add .
        git commit -m "taken vectra file from personalRepo"
        git push origin master
  
