name: Sync Repository
permissions:
  contents: write
on:
  push:
    branches:
      - master  

jobs:
  sync:
    runs-on: windows-latest
    permissions: 
      contents: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Push to second repository
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.SYNCINGTOKEN }} 
        branch: master
        repository: Devarapallivamsi/personalRepo
