name: Sync Repository

on:
  push:
    branches:
      - master  

jobs:
  sync:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Push to second repository
      uses: ad-m/github-push-action@master
      with:
        permissions: write-all
        github_token: ${{ secrets.newToken }} 
        branch: master
        repository: Devarapallivamsi/personalRepo
